name: Deploy Portfolio

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to VPS
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      cd /home/vivek_soniLess/projects/portfolio-vivek
                      git pull origin main
                      pnpm install --config.strict-peer-dependencies=false
                      pnpm build
                      pm2 restart portfolio
